int sp_intern_Triangle_thread(void* reserved)
{
	//endless drawing loop
	while (spScanLineMessage)
	{
		//something in the stack?
		SDL_mutexP(spScanLineMutex);
		if (spScanLineBegin != spScanLineEnd)
		{
			SDL_mutexV(spScanLineMutex);
			switch (spScanLineCache[spScanLineBegin].mode)
			{
				case 0: //Triangle
				{
					if ( spScanLineCache[spScanLineBegin].blending == SP_ONE )
					{
						if ( spScanLineCache[spScanLineBegin].usePattern )
						{
							if ( spScanLineCache[spScanLineBegin].zSet )
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_ztest_zset_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_zset_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
							else
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_ztest_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
						}
						else
						{
							if ( spScanLineCache[spScanLineBegin].zSet )
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_ztest_zset(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_zset(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
							else
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_ztest(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
						}
					}
					else
					{
						if ( spScanLineCache[spScanLineBegin].usePattern )
						{
							if ( spScanLineCache[spScanLineBegin].zSet )
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_blending_ztest_zset_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_blending_zset_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
							else
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_blending_ztest_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_blending_pattern(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
						}
						else
						{
							if ( spScanLineCache[spScanLineBegin].zSet )
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_blending_ztest_zset(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_blending_zset(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
							else
							{
								if ( spScanLineCache[spScanLineBegin].zTest )
									sp_intern_Triangle_blending_ztest(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.z1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.z2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.z3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
								else
									sp_intern_Triangle_blending(
										spScanLineCache[spScanLineBegin].primitive.triangle.x1,
										spScanLineCache[spScanLineBegin].primitive.triangle.y1,
										spScanLineCache[spScanLineBegin].primitive.triangle.x2,
										spScanLineCache[spScanLineBegin].primitive.triangle.y2,
										spScanLineCache[spScanLineBegin].primitive.triangle.x3,
										spScanLineCache[spScanLineBegin].primitive.triangle.y3,
										spScanLineCache[spScanLineBegin].primitive.triangle.color,
										spScanLineCache[spScanLineBegin].pattern,
										spScanLineCache[spScanLineBegin].blending);
							}
						}
					}
					break;
				}
				case 1: //texTriangle
				{
					sp_intern_Triangle_blending_tex_ztest_zset_alpha_pattern(
						spScanLineCache[spScanLineBegin].primitive.texTriangle.x1,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.y1,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.z1,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.u1,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.v1,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.x2,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.y2,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.z2,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.u2,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.v2,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.x3,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.y3,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.z3,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.u3,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.v3,
						spScanLineCache[spScanLineBegin].primitive.texTriangle.color);
					break;
				}
				case 2: //perspectiveTexTriangle
				{
					sp_intern_Triangle_blending_tex_ztest_zset_alpha_pattern_perspect(
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.x1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.y1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.z1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.u1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.v1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.w1,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.x2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.y2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.z2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.u2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.v2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.w2,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.x3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.y3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.z3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.u3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.v3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.w3,
						spScanLineCache[spScanLineBegin].primitive.perspectiveTexTriangle.color);
					break;
				}
			}
			SDL_mutexP(spScanLineMutex);
			spScanLineBegin = (spScanLineBegin+1) & SP_MAX_SCANLINES_MOD;
			SDL_mutexV(spScanLineMutex);
		}
		else
		{
			SDL_mutexV(spScanLineMutex);
			spSleep(SP_MAX_SCANLINES_WAIT_TIME);
		}
	}
}
